# nacos 注册中心配置
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.1.125:8848
      config:
        namespace: 43069866-d4b7-4f71-94c8-dca6dacdd2fa
    # oss 文件上传服务器配置
    alicloud:
      access-key: LTAI4FwvfjSycd1APnuG9bjj
      secret-key: O6xaxyiWfSIitcOkSuK27ju4hXT5Hl
      oss:
        endpoint: oss-cn-beijing.aliyuncs.com
        bucket: mygulimall-jx
  # 服务名称
  application:
    name: gulimall-third-party
# 指定端口
server:
  port: 30000